using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CarAssistant
{
	public enum Brand
	{
        Alfa_Romeo,
        AMC,
        Aston_Martin,
        Audi,
        Autosan,
        Bentley‎,
        BMW‎,
        Bugatti‎,
        Buick‎,
        Cadillac‎,
        Chevrolet‎,
        Chrysler‎,
        Citroën‎, 
        Dacia‎,
        Daewoo‎,
        Dodge‎,
        Ferrari‎,
        Fiat‎,
        Ford‎,
        FSO‎,
        GAZ‎,
        Gumpert,
        Jelcz‎,        
        Honda,
        Hummer‎,
        Hyundai,
        Ikarus‎,
        Infiniti,
        Isuzu‎,
        Iveco‎,
        Jaguar,
        Jeep‎,
        Kia‎,
        Koenigsegg‎,
        Lamborghini‎, 
        Lancia‎,
        Land_Rover‎,
        Lexus‎,
        Lincoln‎,
        Lotus,
        Łada,
        MAN,
        Maserati‎,
        Maybach‎,
        Mazda‎,
        McLaren,
        Mercedes_Benz‎,
        Mini‎,
        Mitsubishi‎,
        Moskwicz,
        Neoplan,
        Nissan,
        Opel‎,
        Pagani‎,
        Peugeot‎,
        Porsche‎,
        Reliant‎,
        Renault‎,
        Rolls_Royce,
        Rover‎,
        Saab‎,
        Saturn,
        Scania‎,
        SEAT,
        Škoda‎,
        Smart‎,
        Solaris‎,
        SsangYong,
        Star‎,
        Subaru‎,
        Suzuki,
        Tatra,
        Tesla‎,
        Toyota‎,
        UAZ,
        Vauxhall,
        Volkswagen‎,
        Volvo,
        Zastava‎,
        ZiŁ‎,
        //Abarth,
        //AC,
        // Acura,
        //AEC‎,
        //Allard‎,
        // Alvis‎, 
        //Amherst‎,
        //   ARO,
        //  Ascari,
        //Austin‎,
        //Auto_Union,
        //Autobianchi,
        //  Avia‎,
        //Bedford‎, 
        //   Benz‎, 
        //Brilliance‎,
        //Bristol‎,
        //British_Motor_Corporation‎,
        // Brockway‎,
        //Büssing‎,
        //BYD‎,
        //Castrosua‎,
        //Caterham‎,
        //Chery‎,
        //Contrac‎,
        //Csepel‎,
        //   DAF‎,
        // Daihatsu‎, 
        //  Daimler‎,
        //   Dallara‎,
        // Darracq‎,
        // De_Tomaso‎,
        //DeSoto,
        //  DKW‎,
        //     DS‎,
        //    Eagle‎,
        //Edsel‎,
        //  Estonia‎,
        //     FAW‎,
        //    GMC‎,
        //  Hillman‎,
        //  Hino‎,
        // Hispano_Suiza‎,
        //    Holden‎, 
        //     HSV‎,
        //     Hudson‎,
        //  IFA,
        //  Innocenti‎,
        //   Intrall‎,
        //  Iran_Khodro‎,
        //   Isdera‎, 
        //   IŻ‎,
        //  Jensen‎,
        //   KrAZ,
        //   Lagonda‎,
        //    Lanchester,
        //    Laraki‎,
        //   Laurin_Klement‎,       
        //    Leyland,
        //     Liebherr,
        //     Ligier‎,
        //    Maruti‎,
        //     Matra,
        //       Melkus‎,
        //   Mercury‎,
        //      MG‎,
        //    Monteverdi,
        //    Moretti‎,
        //    Morgan‎,
        //     Morris,
        //   Noble,
        //  NSU‎,
        //   Oldsmobile‎,
        // Peel‎,
        //  Pierce_Arrow‎,
        //   Packard‎,
        //  Panhard‎,
        //  Panoz‎,
        //   Pegaso‎,
        //   Plymouth‎,
        //   Pontiac,
        //   Proton‎,
        //  Puma,
        //    PZInż,
        //     RAF‎,
        //     Rambler,
        //   Riley,
        //     Roewe,
        //      Ruf‎,
        //    Sisu,
        //  Saleen‎,
        //SAMIL‎,
        //   Gibbs,
        //   LDV‎,
        //  Stanley,
        //   Scion,
        //      Shelby‎,
        //     Simca‎,
        //     Singer‎,
        //      Spyker‎,
        //    Steyr,
        //      Stutz‎,
        //      Talbot,
        //     Tata_Motors‎,
        //      Tofaş‎,
        //     Triumph‎,
        //     TVR,
        //    Ural,
        //     Vector‎,
        //    Veritas,
        //   WaterCar‎,
        // Wiesmann‎,
        // Wolseley,
        //ZAZ‎,
    }
}
